@startuml

package annotations {
    class NotNull {
    }

    class ParameterRange {
        +double min()
        +double max()
    }

    class TestConfig {
        +Class<? extends Throwable> expectedException()
        +boolean happy()

        class None extends Throwable
    }
}

@enduml
